# Generated by Django 6.0.7 on 2026-07-29 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('event_date', models.DateField()),
                ('category_code', models.CharField(max_length=16)),
                ('actor_id', models.CharField(blank=True, max_length=32)),
                ('base_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('adjustment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('state', models.CharField(max_length=16)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='tenancy.location')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='tenancy.org')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('raw_record_ref', models.CharField(max_length=64)),
                ('recorded_on', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('raw_value', models.CharField(blank=True, max_length=32)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='tenancy.location')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='tenancy.org')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='recon.record')),
            ],
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(choices=[('MISSING_IN_B', 'Confirmed in System A, no entry in System B'), ('UNMATCHED_B_REFERENCE', 'System B entry references a record System A does not have'), ('DUPLICATE_ENTRY', 'Same entry duplicated in System B'), ('VALUE_MISMATCH', 'Recorded value disagrees between the two systems'), ('MISSING_VALUE', 'System B entry has no value recorded'), ('LOCATION_MISMATCH', 'The two systems disagree on which location this belongs to'), ('DATE_MISMATCH', 'The two systems disagree on the date'), ('VOIDED_BUT_PRESENT', 'System A voided this record but System B still carries it as live')], max_length=32)),
                ('summary', models.TextField()),
                ('detail', models.JSONField(default=dict)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='tenancy.location')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='tenancy.org')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='recon.entry')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='recon.record')),
            ],
            options={
                'db_table': 'recon_exception',
            },
        ),
    ]
